### PR TITLE
Update chat.revolt.RevoltDesktop.yaml

### PR DESCRIPTION
**Pull request by OrioleNix**
A Build Test so that the revolt SDK and Base will no longer be EOL, uncertain of it's effectiveness.

### CODE REVIEW

**Comment by OrioleNix** [comment]
New Build Test required

**Comment by OrioleNix** [comment]
One more build, hopefully this works, if it doesn't, it doesn't.

**Comment by OrioleNix** [comment]
Having condensed, and tested, this should be upgraded as soon as we have a second point of reference

**Comment by OrioleNix** [comment]
if yall have any issues let me know, but if not I don't know why we can't just merge this already

**Comment by dusansimic** [comment]
Thanks for the contribution! I can see that desktop repo has a deprecation notice and there is no clear sign of the new desktop app release. At some point it should be discussed upstream whether the desktop app is actually deprecated or not.

**Pull request merged**
